import { FileNode } from '../store/useRepoStore';

export interface RepoChange {
  id: string;
  type: 'move' | 'add' | 'delete';
  path: string;            // Current path (or deleted path)
  oldPath?: string;        // Previous path if moved
  nodeType: 'file' | 'folder';
  label: string;
  isNestedUnderMovedParent?: boolean;
}

export interface RepoDiff {
  changes: RepoChange[];
  topLevelChanges: RepoChange[];
  totalCount: number;
}

interface FlatNode {
  id: string;
  value: string;
  label: string;
  type: 'file' | 'folder';
}

/**
 * Ensures all nodes in the tree have unique, persistent ids.
 */
export function assignNodeIds(nodes: FileNode[], prefix: string = 'node'): FileNode[] {
  return nodes.map((node) => {
    const id = node.id || `${prefix}-${node.type}-${node.value.replace(/[^a-zA-Z0-9]/g, '_')}`;
    const copy: FileNode = {
      ...node,
      id,
    };
    if (node.children) {
      copy.children = assignNodeIds(node.children, prefix);
    }
    return copy;
  });
}

/**
 * Flattens tree into a Map of id -> FlatNode
 */
function flattenTree(nodes: FileNode[]): Map<string, FlatNode> {
  const map = new Map<string, FlatNode>();

  const traverse = (list: FileNode[]) => {
    for (const item of list) {
      if (item.id) {
        map.set(item.id, {
          id: item.id,
          value: item.value,
          label: item.label,
          type: item.type,
        });
      }
      if (item.children) {
        traverse(item.children);
      }
    }
  };

  traverse(nodes);
  return map;
}

/**
 * Computes reactive diff between initial baseline tree and current tree.
 */
export function computeRepoDiff(initialTree: FileNode[] | null, currentTree: FileNode[]): RepoDiff {
  if (!initialTree) {
    return { changes: [], topLevelChanges: [], totalCount: 0 };
  }

  const initialMap = flattenTree(initialTree);
  const currentMap = flattenTree(currentTree);

  const changes: RepoChange[] = [];

  // 1. Detect Moves & Adds in current tree
  for (const [id, currNode] of currentMap.entries()) {
    const initNode = initialMap.get(id);
    if (initNode) {
      if (initNode.value !== currNode.value) {
        changes.push({
          id,
          type: 'move',
          path: currNode.value,
          oldPath: initNode.value,
          nodeType: currNode.type,
          label: currNode.label,
        });
      }
    } else {
      changes.push({
        id,
        type: 'add',
        path: currNode.value,
        nodeType: currNode.type,
        label: currNode.label,
      });
    }
  }

  // 2. Detect Deletes (items in initialMap not present in currentMap)
  for (const [id, initNode] of initialMap.entries()) {
    if (!currentMap.has(id)) {
      changes.push({
        id,
        type: 'delete',
        path: initNode.value,
        nodeType: initNode.type,
        label: initNode.label,
      });
    }
  }

  // Identify top-level changes (to avoid redundant bash git mv/rm on children when parent folder moved/deleted)
  const movedFolders = changes.filter((c) => c.type === 'move' && c.nodeType === 'folder');
  const deletedFolders = changes.filter((c) => c.type === 'delete' && c.nodeType === 'folder');
  const addedFolders = changes.filter((c) => c.type === 'add' && c.nodeType === 'folder');

  for (const ch of changes) {
    if (ch.type === 'move' && ch.oldPath) {
      const isNested = movedFolders.some(
        (f) =>
          f.id !== ch.id &&
          ch.oldPath!.startsWith(f.oldPath! + '/') &&
          ch.path.startsWith(f.path + '/')
      );
      if (isNested) {
        ch.isNestedUnderMovedParent = true;
      }
    } else if (ch.type === 'delete') {
      const isNested = deletedFolders.some(
        (f) => f.id !== ch.id && ch.path.startsWith(f.path + '/')
      );
      if (isNested) {
        ch.isNestedUnderMovedParent = true;
      }
    } else if (ch.type === 'add') {
      const isNested = addedFolders.some(
        (f) => f.id !== ch.id && ch.path.startsWith(f.path + '/')
      );
      if (isNested) {
        ch.isNestedUnderMovedParent = true;
      }
    }
  }

  const topLevelChanges = changes.filter((c) => !c.isNestedUnderMovedParent);

  return {
    changes,
    topLevelChanges,
    totalCount: topLevelChanges.length,
  };
}

/**
 * Generates runnable bash commands for the changes.
 */
export function generateShellScript(diff: RepoDiff): string {
  const lines: string[] = [
    '#!/usr/bin/env bash',
    '# Generated by RepoArchitect - Bundle Changes Exporter',
    'set -e',
    '',
  ];

  const norm = (p: string) => p.replace(/^\/+/, '');
  const getDir = (p: string) => {
    const parts = norm(p).split('/');
    parts.pop();
    return parts.join('/');
  };

  const { topLevelChanges } = diff;

  // 1. mkdir directories for moves and adds
  const dirsToCreate = new Set<string>();
  for (const ch of topLevelChanges) {
    if (ch.type === 'move' || ch.type === 'add') {
      const dir = ch.nodeType === 'folder' && ch.type === 'add' ? norm(ch.path) : getDir(ch.path);
      if (dir) {
        dirsToCreate.add(dir);
      }
    }
  }

  if (dirsToCreate.size > 0) {
    lines.push('# 1. Ensure target directories exist');
    for (const d of Array.from(dirsToCreate).sort()) {
      lines.push(`mkdir -p "${d}"`);
    }
    lines.push('');
  }

  // 2. git mv commands
  const moves = topLevelChanges.filter((ch) => ch.type === 'move');
  if (moves.length > 0) {
    lines.push('# 2. Relocate files and directories via Git');
    for (const m of moves) {
      if (m.oldPath) {
        lines.push(`git mv "${norm(m.oldPath)}" "${norm(m.path)}"`);
      }
    }
    lines.push('');
  }

  // 3. touch / create added files
  const adds = topLevelChanges.filter((ch) => ch.type === 'add');
  if (adds.length > 0) {
    lines.push('# 3. Create newly added files');
    for (const a of adds) {
      if (a.nodeType === 'file') {
        lines.push(`touch "${norm(a.path)}"`);
      }
    }
    lines.push('');
  }

  // 4. rm commands
  const deletes = topLevelChanges.filter((ch) => ch.type === 'delete');
  if (deletes.length > 0) {
    lines.push('# 4. Remove deleted files/directories');
    for (const d of deletes) {
      if (d.nodeType === 'folder') {
        lines.push(`rm -rf "${norm(d.path)}"`);
      } else {
        lines.push(`rm -f "${norm(d.path)}"`);
      }
    }
    lines.push('');
  }

  lines.push('echo "✓ All repository bundle changes applied successfully!"');
  return lines.join('\n');
}

/**
 * Generates a structured prompt mapping old paths to new paths with instructions to update imports.
 */
export function generateAgentPrompt(diff: RepoDiff): string {
  const norm = (p: string) => p.replace(/^\/+/, '');
  const lines: string[] = [
    'I have reorganized the repository file layout. Please analyze the following path changes and update all relevant import statements, module exports, and relative file references across the codebase:',
    '',
    '### Path Changes:',
  ];

  const moves = diff.changes.filter((c) => c.type === 'move');
  const adds = diff.changes.filter((c) => c.type === 'add');
  const deletes = diff.changes.filter((c) => c.type === 'delete');

  if (moves.length > 0) {
    lines.push('#### Relocated / Renamed:');
    for (const m of moves) {
      lines.push(`- \`${norm(m.oldPath!)}\` ➔ \`${norm(m.path)}\` (${m.nodeType})`);
    }
    lines.push('');
  }

  if (adds.length > 0) {
    lines.push('#### Newly Added:');
    for (const a of adds) {
      lines.push(`- \`${norm(a.path)}\` (${a.nodeType})`);
    }
    lines.push('');
  }

  if (deletes.length > 0) {
    lines.push('#### Removed:');
    for (const d of deletes) {
      lines.push(`- \`${norm(d.path)}\` (${d.nodeType})`);
    }
    lines.push('');
  }

  lines.push('### Refactoring Instructions:');
  lines.push('1. Scan all files that import from the relocated or removed paths.');
  lines.push('2. Update the import paths to point accurately to their new locations.');
  lines.push('3. Check relative import paths inside the moved files themselves to verify they still resolve.');
  lines.push('4. If any exports or files were removed, cleanly remove dead references or adjust consumers.');
  lines.push('5. Ensure TypeScript module resolution and build pipelines remain green.');

  return lines.join('\n');
}
